#!/usr/bin/env bash
#  Script bach FizzBuzz
counter=1
while [ $counter -le 100 ];
do
if [ $((counter%3)) == 0 -a $((counter%5)) == 0 ]
then
    echo "FizzBuzz"
elif [ $((counter%3)) == 0 ]
then
    echo "Fizz"
elif [ $((counter%5)) == 0 ]
then
    echo "Buzz"
else
    echo $counter
fi
    let counter=counter+1
done
